name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Every day at midnight UTC
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: osmarbetancourt
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Bogota
          filename: metrics.svg
          base: header, activity, community, repositories, metadata
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, jupyter notebook
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_activity: yes
          plugin_activity_limit: 10
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_trophies: yes
          plugin_trophies_sections: all
          plugin_trophies_threshold: C
          plugin_stargazers: yes
          plugin_lines: yes
          plugin_contributors: yes
          plugin_repositories: 100
